#!/usr/bin/env python

from datetime import datetime, timezone
import paho.mqtt.client as mqtt 
import os
from time import sleep
import influxdb_client
import json
import sys
import RPi.GPIO as GPIO
from queue import Queue
from influxdb_client.client.write_api import SYNCHRONOUS
from influxdb_client.domain.write_precision import WritePrecision

sys.path.insert(1, '/home/pi/config')
from setup import *

# 2.27124707 liters per hour
# 2271.24707 milliliters
# 2271.24707 / 3600 = 0.63090196 = Milliliters per second.
mLitersPerSec = 0.63090196
boilerSensors = "esp5bc674"
burnerGpio = "33"
boilerTemp = "28b867746008f"
waterTemp = "28e1747360083"
shellynumber = 1

def saveTemperature(write_api, data, ts):
    temperature = float(data['value'])
    datats = int(data['ts'])
    text = ""

    if data['sensor'] == boilerTemp:
        p = influxdb_client.Point("boiler").tag("name", "temperatures").field("boilerTemperature", temperature).time(1000 * datats,write_precision=WritePrecision.MS)
        text = "boilerTemp"
    if data['sensor'] == waterTemp:
        p = influxdb_client.Point("boiler").tag("name", "temperatures").field("hotWaterTemperature", temperature).time(1000 * datats,write_precision=WritePrecision.MS)
        text = "hotWater"
    write_api.write(bucket="forever", org=influx_credentials.org, record=p)
    print(datetime.now(), text + "temperature:", temperature, "delay:",ts - datats)


def saveState(write_api, data, ts):
    state = int(data['value'])
    datats = int(data['ts'])
    duration = int(data['duration'])
    closems = 1000 * (datats -1)

    if state == 0:
        if duration > 0:
            liters = round(float(mLitersPerSec * duration / 1000), 5)
            p = influxdb_client.Point("liters").tag("name", "heatoil").field("consumed", liters).time(1000 * datats,write_precision=WritePrecision.MS)
            write_api.write(bucket="forever", org=influx_credentials.org, record=p)
            
            p = influxdb_client.Point("state").tag("name", "burner").field("on", 20).time(closems,write_precision=WritePrecision.MS)
            write_api.write(bucket="forever", org=influx_credentials.org, record=p)
            p = influxdb_client.Point("state").tag("name", "burner").field("on", 0).time(1000 * datats,write_precision=WritePrecision.MS)
            write_api.write(bucket="forever", org=influx_credentials.org, record=p)
            print(datetime.now(), "state:", state, "liters:", liters,  "delay:",ts - data['ts'])

    else:
        if duration > 0:
            p = influxdb_client.Point("liters").tag("name", "idle").field("seconds", duration).time(1000 * datats,write_precision=WritePrecision.MS)
            write_api.write(bucket="forever", org=influx_credentials.org, record=p)

            p = influxdb_client.Point("state").tag("name", "burner").field("on", 0).time(closems,write_precision=WritePrecision.MS)
            write_api.write(bucket="forever", org=influx_credentials.org, record=p)
            p = influxdb_client.Point("state").tag("name", "burner").field("on", 20).time(1000 * datats,write_precision=WritePrecision.MS)
            write_api.write(bucket="forever", org=influx_credentials.org, record=p)
            print(datetime.now(), "state:", state, "delay:",ts - datats)


def saveRelay(write_api, data):
    contact = int(data['contact'])
    tagname = "unknown"
    power = 0

    if contact == 0:
        tagname = "elheater2kw"
        power = 2

    elif contact == 1:
        tagname = "test"

    elif contact == 2:
        tagname = "elheater4kw"
        power = 4

    elif contact == 3:
        tagname = "burner_allowed"
        power = 20

    else:
        return

    if bool(data['state']) == False:
        prevpower = power
        power = 0 
    else: 
        prevpower = 0
    datats = int(data['ts']) * 1000
    prevts = datats - 100 # minus 100ms
    

    p1 = influxdb_client.Point("state")
    p1.time(prevts, write_precision=WritePrecision.MS)
    p1.field("on", prevpower)

    p2 = influxdb_client.Point("state")
    p2.time(datats, write_precision=WritePrecision.MS)
    p2.field("on", power)


    p1.tag("name", tagname)
    p2.tag("name", tagname)

    write_api.write(bucket="forever", org=influx_credentials.org, record=p1)
    write_api.write(bucket="forever", org=influx_credentials.org, record=p2)

    print(datetime.now(), "relay:", contact, "power:", power, "prevpower:", prevpower)


def saveData(myData):

    dbclient = influxdb_client.InfluxDBClient(
        url=influx_credentials.url,
        token=influx_credentials.token,
        org=influx_credentials.org
    )
    write_api = dbclient.write_api(write_options=SYNCHRONOUS)
    now = int(datetime.now(timezone.utc).timestamp())
    id = myData['id']

    if id == "state":
        saveState(write_api, myData, now)
        return

    elif id == "temperature":
        saveTemperature(write_api, myData, now)

    elif id == "relay":
        saveRelay(write_api,myData)

    else:
        pass


def on_message(client, userdata, message):
    msgqueue.put(message.payload)

def logger(client, userdata, level, buff):
    print("level=",level," buff=",buff)


def on_connect(client, userdata, flags, rc):
    global connected
    if (rc==0):
        topics = [(mqtt_broker.topic_prefix + "/" + boilerSensors + "/parameters/#",0),
                  (mqtt_broker.topic_prefix + "/relay/+/shelly" + str(shellynumber) + "/state", 0)]
        client.subscribe(topics)
        connected = True
    else:
        print("connection failed, rc=",rc)            
        connected = False


def on_disconnect(client, userdata, rc):
    if rc != 7:
        try:
            client.reconnect()
        except:
            print(datetime.now(),"reconnect failed, waiting...")
            sleep(30)

    else:
        sleep(30)

led = 13
GPIO.setwarnings(False) 
GPIO.setmode(GPIO.BCM)
GPIO.setup(led, GPIO.OUT)

msgqueue = Queue(maxsize=4)    
pid = os.getpid()

client = mqtt.Client("relaystate_saver:" + str(pid)) #create new instance
client.on_connect = on_connect
client.on_message = on_message
client.on_disconnect = on_disconnect
client.connect(mqtt_broker.address,port=mqtt_broker.port, keepalive=60) 
print(datetime.now(), "Start")
client.loop_start()


while (True):
    try:
        data = msgqueue.get(block=True)
        if data is None:
            continue
        GPIO.output(led, GPIO.LOW)
        saveData(json.loads(data))
        sys.stdout.flush()
        GPIO.output(led, GPIO.HIGH)

    except KeyboardInterrupt:
        client.disconnect()
        GPIO.output(led, GPIO.HIGH)
        exit(0)

    except:
        raise        
