#!/usr/bin/env python

import time
from datetime import datetime
from datetime import timezone
import paho.mqtt.client as mqtt 
import os
import influxdb_client
import json
import sys
import RPi.GPIO as GPIO
from queue import Queue
from influxdb_client.client.write_api import SYNCHRONOUS
from influxdb_client.domain.write_precision import WritePrecision

sys.path.insert(1, '/home/pi/config')
from influx_credentials import *


wattsPerTick = 36

def saveData(myData):

    dbclient = influxdb_client.InfluxDBClient(
        url=influx_credentials.url,
        token=influx_credentials.token,
        org=influx_credentials.org
    )
    write_api = dbclient.write_api(write_options=SYNCHRONOUS)

    value = int(myData['value'])
    watts = wattsPerTick * value;
    p = influxdb_client.Point("watts").tag("name", "electricity").field("consumed", watts).time(1000 * myData['ts'],write_precision=WritePrecision.MS)
    write_api.write(bucket="weekly", org=influx_credentials.org, record=p)
       
    now = int(datetime.now(timezone.utc).timestamp())
    print(datetime.now(), "count=", value, ":", watts, "W delay:",now - myData['ts'])


def on_message(client, userdata, message):
    msgqueue.put(message.payload)

def logger(client, userdata, level, buff):
    print("level=",level," buff=",buff)


def on_connect(client, userdata, flags, rc):
    global connected
    if (rc==0):
        client.subscribe("home/kallio/esp277998/parameters/counter/26")
        connected = True
    else:
        print("connection failed, rc=",rc)            
        connected = False

def on_disconnect(client, userdata, rc):
    client.reconnect()

led = 13
GPIO.setmode(GPIO.BCM)
GPIO.setup(led, GPIO.OUT)

msgqueue = Queue(maxsize=4)    
pid = os.getpid()

client = mqtt.Client("influx_electricity_saver:" + str(pid)) #create new instance
client.on_connect = on_connect
client.on_message = on_message
client.on_disconnect = on_disconnect
client.connect(mqtt_broker.address,port=mqtt_broker.port, keepalive=60) 
print(datetime.now(), "Start")
client.loop_start()


while (True):
    data = msgqueue.get(block=True)
    if data is None:
        continue
    GPIO.output(led, GPIO.LOW)
    saveData(json.loads(data))
    sys.stdout.flush()
    GPIO.output(led, GPIO.HIGH)
