#!/usr/bin/env python

from datetime import datetime
import paho.mqtt.client as mqtt 
import os
import influxdb_client
import json
import sys
from queue import Queue
from influxdb_client.client.write_api import SYNCHRONOUS
from influxdb_client.domain.write_precision import WritePrecision


sys.path.insert(1, '../config')
from influx_credentials import *


def saveData(recData):
    client = influxdb_client.InfluxDBClient(
        url=influx_credentials.url,
        token=influx_credentials.token,
        org=influx_credentials.org
    )

    ts = int(recData['ts'])
    cents = int(float(recData['price'])*100)
    print(datetime.now(),msgqueue.qsize(), ts, cents)
    
    write_api = client.write_api(write_options=SYNCHRONOUS)
    p = influxdb_client.Point("euros").tag("name","elprice").field("price", cents).time(1000 * ts,write_precision=WritePrecision.MS)
    write_api.write(influx_credentials.bucket, org=influx_credentials.org, record=p)


def on_message(client, userdata, message):
    msgqueue.put(message.payload)


def on_connect(client, userdata, flags, rc):
    global connected
    if (rc==0):
        client.subscribe("home/kallio/elprice/#")
        connected = True
    else:
        print("connection failed, rc=",rc)            
        connected = False

def on_disconnect(client, userdata, rc):
    client.reconnect()

msgqueue = Queue(maxsize=25)    
pid = os.getpid()

client = mqtt.Client("influx_elprice_saver:" + str(pid))
client.on_connect = on_connect
client.on_message = on_message
client.on_disconnect = on_disconnect
client.connect(mqtt_broker.address,port=mqtt_broker.port, keepalive=60) 
print(datetime.now(), "Start")
client.loop_start()

while (True):
    try:
        data = msgqueue.get(block=True)
        if data is None:
            continue
        saveData(json.loads(data))
        sys.stdout.flush()

    except KeyboardInterrupt:
        client.disconnect()
        exit(0)

    except:
        raise        
