#!/usr/bin/env python

from datetime import datetime
import paho.mqtt.client as mqtt 
import os
import time
import influxdb_client
import json
import sys
import RPi.GPIO as GPIO
from queue import Queue

import influxdb_client
from influxdb_client.client.write_api import SYNCHRONOUS
from influxdb_client.domain.write_precision import WritePrecision

sys.path.insert(1, '/home/pi/config')
from influx_credentials import *


def saveData(recData):
    storage = "forever"

    client = influxdb_client.InfluxDBClient(
        url=influx_credentials.url,
        token=influx_credentials.token,
        org=influx_credentials.org
    )

    write_api = client.write_api(write_options=SYNCHRONOUS)
    ts = int(recData['ts'])
    print(ts, datetime.fromtimestamp(ts))

    p = influxdb_client.Point("uvindex").tag("name","weather").field("solar", int(recData['uvindex'])).time(ts,write_precision=WritePrecision.S)
    write_api.write(bucket=storage, org=influx_credentials.org, record=p)

    p = influxdb_client.Point("radiation").tag("name","weather").field("solar", int(recData['solarradiation'])).time(ts,write_precision=WritePrecision.S)
    write_api.write(bucket=storage, org=influx_credentials.org, record=p)

    if (recData['solarenergy']):
        p = influxdb_client.Point("energy").tag("name","weather").field("solar", float(recData['solarenergy'])).time(ts,write_precision=WritePrecision.S)
        write_api.write(bucket=storage, org=influx_credentials.org, record=p)

    p = influxdb_client.Point("snow").tag("name","weather").field("efficiency", int(recData['snow'])).time(ts,write_precision=WritePrecision.S)
    write_api.write(bucket=storage, org=influx_credentials.org, record=p)

    p = influxdb_client.Point("temperature").tag("name","weather").field("efficiency", float(recData['temperature'])).time(ts,write_precision=WritePrecision.S)
    write_api.write(bucket=storage, org=influx_credentials.org, record=p)


def on_message(client, userdata, message):
    msgqueue.put(message.payload)

def on_connect(client, userdata, flags, rc):
    global connected
    if (rc==0):
        client.subscribe("home/kallio/weather/#")
        connected = True
    else:
        print("connection failed, rc=",rc)            
        connected = False

def on_disconnect(client, userdata, rc):
    if rc!=7:
        client.reconnect()
    else:
        time.sleep(30)


led = 13
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(led, GPIO.OUT)

msgqueue = Queue(maxsize=25)    
pid = os.getpid()

client = mqtt.Client("influx_weather_saver:" + str(pid))
client.on_connect = on_connect
client.on_message = on_message
client.on_disconnect = on_disconnect
client.connect(mqtt_broker.address,port=mqtt_broker.port, keepalive=60) 
print(datetime.now(), "Start")
client.loop_start()

while (True):
    try:
        data = msgqueue.get(block=True)
        if data is None:
            continue
        GPIO.output(led, GPIO.LOW)
        saveData(json.loads(data))
        sys.stdout.flush()
        GPIO.output(led, GPIO.HIGH)

    except KeyboardInterrupt:
        client.disconnect()
        client.loop_stop()
        exit(0)

    except:
        raise
