#!/usr/bin/env python

from datetime import datetime
import json
import sys
import time
import os
import RPi.GPIO as GPIO
import paho.mqtt.client as mqtt 
from queue import Queue

import influxdb_client
from influxdb_client.client.write_api import SYNCHRONOUS
from influxdb_client.domain.write_precision import WritePrecision

sys.path.insert(1, '/home/pi/config')
from setup import mqtt_broker, influx_credentials


def saveData(myData):
    bucket = "yearly"

    client = influxdb_client.InfluxDBClient(
        url   = influx_credentials.url,
        token = influx_credentials.token,
        org   = influx_credentials.org
    )
 

    write_api = client.write_api(write_options=SYNCHRONOUS)

    ts = int(myData['ts']) 
    now = int(time.time())
    if now - ts > 86400 * 2:
        print(datetime.now(),"too old data, dont save it.")
        return

    string1 = myData['string1']
    string2 = myData['string2']
    device  = myData['dev']
    grid    = myData['grid']


    p = influxdb_client.Point("solis").tag("device",device)
    p.time(ts,write_precision=WritePrecision.S)

    p.field("power1", float(string1['power']))
    p.field("current1", float(string1['current']))
    p.field("voltage1", float(string1['voltage']))

    p.field("power2",   float(string2['power']))
    p.field("current2", float(string2['current']))
    p.field("voltage2", float(string2['voltage']))

    p.field("igbt_temp", myData['inverter_temp'])

    p.field("totalpower", myData['acpower'] * 1000)
    p.field("gridfreq", float(grid['freq']))

    p.field("uac1", float(grid['phases'][0]['voltage']))
    p.field("uac2", float(grid['phases'][1]['voltage']))
    p.field("uac3", float(grid['phases'][2]['voltage']))

    p.field("iac1", float(grid['phases'][0]['current']))
    p.field("iac2", float(grid['phases'][1]['current']))
    p.field("iac3", float(grid['phases'][2]['current']))

    write_api.write(bucket=bucket, org=influx_credentials.org, record=p)

    print(datetime.now(), "Saved")

def on_message(client, userdata, message):
    msgqueue.put(message.payload)

def on_connect(client, userdata, flags, rc):
    global connected
    if (rc==0):
        client.subscribe(mqtt_broker.topic_prefix + "/+/solarpower")
        connected = True
    else:
        print("connection failed, rc=",rc)            
        connected = False

def on_disconnect(client, userdata, rc):
    if rc!=7:
        try:
            client.reconnect()
        except:
            print(datetime.now(),"reconnect failed, waiting...")
            time.sleep(30)

    else:
        time.sleep(30)



led = 13
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(led, GPIO.OUT)

msgqueue = Queue(maxsize=5)    
pid = os.getpid()

client = mqtt.Client("influx_inverter_saver:" + str(pid))
client.on_connect = on_connect
client.on_message = on_message
client.on_disconnect = on_disconnect
client.connect(mqtt_broker.address,port=mqtt_broker.port, keepalive=60) 
print(datetime.now(), "Start")
client.loop_start()

while (True):
    try:
        data = msgqueue.get(block=True)
        if data is None:
            continue
        GPIO.output(led, GPIO.LOW)
        saveData(json.loads(data))
        sys.stdout.flush()
        GPIO.output(led, GPIO.HIGH)

    except KeyboardInterrupt:
        client.disconnect()
        client.loop_stop()
        GPIO.cleanup()
        exit(0)

    except:
        raise        

