#!/usr/bin/env python

from datetime import datetime
import time
import json
import paho.mqtt.client as mqtt 
from queue import Queue, Empty
import sys

sys.path.insert(1, '../config')
from setup import * mqtt_broker

shellynumber = 1
statsInterval = 300

class relay:
    def __init__(self, index):
        self.index = index
        self.state = False
        self.ts = 0
        self.initdone = False
        self.energy = 0.0
        self.voltage = 0
        self.temperature = 0
        self.current = 0
        self.count = 0

relays = [relay(0),
          relay(1),
          relay(2),
          relay(3)]


def queryStatus(num):
    global shellynumber
    relaymsg = {
        'id': 'status',
        'src': 'shelly' + str(shellynumber) + '/events',
        'method' : 'Switch.GetStatus',
        'params': {
                'id':num
            }
    }
    setrelaytopic="shelly" +str(shellynumber) +"/rpc"
    client.publish(setrelaytopic,json.dumps(relaymsg))


def publishStats():
    global shellynumber

    stats = []
    for rel in relays:
        stats.append(
            {
                'relay':   rel.index,
                'energy' : rel.energy,
                'voltage': rel.voltage,
                'temperature': rel.temperature,
                'current': rel.current,
                'count': rel.count
            })

    relaymsg = {
        'id': 'statistics',
        'device' : 'shelly' + str(shellynumber),
        'ts': int(time.time()),
        'relays': stats
    }
    statisticstopic= mqtt_broker.topic_prefix +"shelly"+ str(shellynumber) + "/statistics"
    client.publish(statisticstopic,json.dumps(relaymsg),qos=0, retain=True)


def publishRelay(rel):
    global shellynumber
    relaymsg = {
        'id': 'relay',
        'device' : 'shelly' + str(shellynumber),
        'contact': rel.index,
        'state': rel.state,
        'ts': rel.ts
    }
    rel.count += 1
    setrelaytopic = mqtt_broker.topic_prefix + "relay/" +str(rel.index) +"/shelly"+ str(shellynumber) + "/state"
    client.publish(setrelaytopic,json.dumps(relaymsg),qos=0, retain=True)

def setRelay(num, state):
    global shellynumber

    relaymsg = {
        'id': 20,
        'src': topics.prefix + 'relayreply',
        'method':'Switch.Set',
        'params': {
                'id':num,
                'on':state
            }
    }
    setrelaytopic="shelly" + str(shellynumber) + "/rpc"
    client.publish(setrelaytopic,json.dumps(relaymsg))


def processData(eldata):
    global relays

    if not (eldata.get('id') is None):
        if (eldata['id'] == 'relay'):
            # actual relay contact needs to be changed
            contact = eldata['contact']
            newstate = eldata['state']
            if relays[contact].state != newstate or relays[contact].initdone == False:
                relays[contact].initdone = True
                setRelay(contact, newstate)

     #{"id":"status","src":"shellypro4pm-30c6f784e78c","dst":"shelly1/events","result":{
     #  "id":0, "source":"UI", "output":true, "apower":0.0, "voltage":237.1, "current":0.000, "pf":0.00, "aenergy":{
     #      "total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1676038428},"temperature":{
     #            "tC":44.2, "tF":111.6}}}

        if (eldata['id'] == 'status'):
            # shelly replied for queryStatus
            result = eldata['result']
            index = int(result['id'])
            if relays[index].ts == 0:
                relays[index].ts = int(time.time())
            relays[index].state = result['output']
            relays[index].voltage = float(result['voltage'])
            relays[index].current = float(result['current'])
            temperatures = result['temperature']
            relays[index].temperature = float(temperatures['tC'])
            print(datetime.now(),"relay",index,"state",result['output'], "volt", relays[index].voltage, "temp",relays[index].temperature, "amps",relays[index].current)


    if not (eldata.get('method') is None):
        method = eldata['method']
        if method == 'NotifyStatus':
            # somebody changed relay status with shelly buttons
            params = eldata['params']
            ts = int(params['ts'])
            
            for rel in relays:
                swname = 'switch:' + str(rel.index)
                if not (params.get(swname) is None):
                    relaydata =  params[swname]
                    if not (relaydata.get('output') is None):
                        state = relaydata['output']
                        if state != rel.state or rel.initdone == False:
                            print(datetime.now(),rel.index,"changed")
                            rel.initdone = True
                            rel.state = state
                            rel.ts = ts
                            publishRelay(rel)
                    if not (relaydata.get('aenergy') is None):
                        energy = relaydata['aenergy']
                        rel.energy = float(energy['total'])
                        rel.ts = int(energy['minute_ts'])


def on_message(client, userdata, message):
    msgqueue.put(message.payload)


def on_connect(client, userdata, flags, rc):
    global connected
    if (rc==0):
        connected = True
    else:
        print(datetime.now(),"connection failed, rc=",rc)
        connected = False

def on_disconnect(client, userdata, rc):
    client.reconnect()

def on_publish(client, userdata,result):
    pass


msgqueue = Queue(maxsize=10)


client = mqtt.Client("shelly" + str(shellynumber)) 
client.on_connect = on_connect
client.on_message = on_message
client.on_publish = on_publish

client.on_disconnect = on_disconnect
client.connect(mqtt_broker.address,port = mqtt_broker.port, keepalive=60) 
print(datetime.utcnow(), "Start")
client.loop_start()


topics = [(topics.prefix + "relay/shelly" + str(shellynumber) + "/setstate",0),
          ("shelly1/events/rpc",0)]
client.subscribe(topics)

waitTime=5 # first statistics after 5 sec
prevStatisticsTS = 0

while True:
    now = int(time.time())
    if now - prevStatisticsTS > statsInterval:
        prevStatisticsTS = now
        publishStats()
        for rel in relays:
            queryStatus(rel.index)

    try:
        data = msgqueue.get(block=True, timeout=waitTime)
        if data is None:
            continue
        msg = json.loads(data)
        processData(msg)

    except Empty:
        publishStats()  # contents are what was in previous queryStatus
        for rel in relays:
            queryStatus(rel.index) # querying again, results are shown later.
        waitTime = statsInterval

    except KeyboardInterrupt:
        client.disconnect()
        exit(0)

    except json.decoder.JSONDecodeError as e:
        print(datetime.utcnow(), "json:", e)
        print(datetime.utcnow(), data)

    except:
        raise        