#!/usr/bin/env python

from datetime import datetime
import time
import json
import paho.mqtt.client as mqtt 
from queue import Queue, Empty
import sys

sys.path.insert(1, '../config')
from setup import *

shellyname = "shelly4"
statsInterval = 300

class relay:
    def __init__(self, index):
        self.index = index
        self.state = False
        self.ts = 0
        self.initdone = False
        self.energy = 0.0
        self.voltage = 0
        self.temperature = 0
        self.current = 0
        self.count = 0

relays = [relay(0),
          relay(1),
          relay(2),
          relay(3)]


def queryStatus(num):
    global shellyname
    relaymsg = {
        'id': 'status',
        'src': shellyname + '/events',
        'method' : 'Switch.GetStatus',
        'params': {
                'id':num
            }
    }
    setrelaytopic=shellyname +"/rpc"
    client.publish(setrelaytopic,json.dumps(relaymsg))


def publishStats():
    global shellyname

    stats = []
    for rel in relays:
        stats.append(
            {
                'relay':   rel.index,
                'energy' : rel.energy,
                'voltage': rel.voltage,
                'temperature': rel.temperature,
                'current': rel.current,
                'count': rel.count
            })

    relaymsg = {
        'id': 'statistics',
        'device' : shellyname,
        'ts': int(time.time()),
        'relays': stats
    }
    statisticstopic= mqtt_broker.topic_prefix +"/" +shellyname + "/statistics"
    client.publish(statisticstopic,json.dumps(relaymsg),qos=0, retain=True)


def publishRelay(rel):
    global shellyname
    relaymsg = {
        'id': 'relay',
        'device' : shellyname,
        'contact': rel.index,
        'state': rel.state,
        'ts': rel.ts
    }
    rel.count += 1
    setrelaytopic = mqtt_broker.topic_prefix + "/relay/" +str(rel.index) + "/" +shellyname + "/state"
    client.publish(setrelaytopic,json.dumps(relaymsg),qos=0, retain=True)

def setRelay(num, state):
    global shellyname

    relaymsg = {
        'id': 20,
        'src': mqtt_broker.topic_prefix + '/relayreply',
        'method':'Switch.Set',
        'params': {
                'id':num,
                'on':state
            }
    }
    setrelaytopic= shellyname + "/rpc"
    client.publish(setrelaytopic,json.dumps(relaymsg))


def processData(eldata):
    global relays

    if not (eldata.get('id') is None):
        if (eldata['id'] == 'relay'):
            # actual relay contact needs to be changed
            contact = eldata['contact']
            newstate = eldata['state']
            if relays[contact].state != newstate or relays[contact].initdone == False:
                relays[contact].initdone = True
                setRelay(contact, newstate)

        if (eldata['id'] == 'status'):
            # shelly replied for queryStatus
            result = eldata['result']
            index = int(result['id'])
            if relays[index].ts == 0:
                relays[index].ts = int(time.time())
            relays[index].state = result['output']
            relays[index].voltage = float(result['voltage'])
            relays[index].current = float(result['current'])
            temperatures = result['temperature']
            relays[index].temperature = float(temperatures['tC'])
            print(datetime.utcnow(),"relay",index,"state",result['output'], "volt", relays[index].voltage, "temp",relays[index].temperature, "amps",relays[index].current)


    if not (eldata.get('method') is None):
        method = eldata['method']
        if method == 'NotifyStatus':
            # somebody changed relay status with shelly buttons
            params = eldata['params']
            ts = int(params['ts'])
            
            for rel in relays:
                swname = 'switch:' + str(rel.index)
                if not (params.get(swname) is None):
                    relaydata =  params[swname]
                    if not (relaydata.get('output') is None):
                        state = relaydata['output']
                        if state != rel.state or rel.initdone == False:
                            print(datetime.utcnow(),rel.index,"changed")
                            rel.initdone = True
                            rel.state = state
                            rel.ts = ts
                            publishRelay(rel)
                    if not (relaydata.get('aenergy') is None):
                        energy = relaydata['aenergy']
                        rel.energy = float(energy['total'])
                        rel.ts = int(energy['minute_ts'])


def on_message(client, userdata, message):
    msgqueue.put(message.payload)


def on_connect(client, userdata, flags, rc):
    global connected
    if (rc==0):
        connected = True
    else:
        print(datetime.utcnow(),"connection failed, rc=",rc)
        connected = False


def on_disconnect(client, userdata, rc):
    print(datetime.utcnow(),"disconnected")
    if rc != 7:
        try:
            client.reconnect()
        except:
            print(datetime.utcnow(),"reconnect failed, waiting...")
            time.sleep(30)
    else:
        time.sleep(1)


def on_publish(client, userdata,result):
    pass

if (len(sys.argv) < 2):
    print("i need shellyname as parameter")
    print("example: ", sys.argv[0], "boilerroom")
    exit(1)
else:
    shellyname = sys.argv[1]

msgqueue = Queue(maxsize=10)


client = mqtt.Client(shellyname) 
client.on_connect = on_connect
client.on_message = on_message
client.on_publish = on_publish

client.on_disconnect = on_disconnect
client.connect(mqtt_broker.address,port = mqtt_broker.port, keepalive=60) 
print(datetime.utcnow(), "Start")
client.loop_start()


topics = [(mqtt_broker.topic_prefix + "/relay/" + shellyname + "/setstate",0),
          (shellyname + "/events/rpc",0)]
client.subscribe(topics)

waitTime=5 # first statistics after 5 sec
prevStatisticsTS = 0

while True:
    now = int(time.time())
    if now - prevStatisticsTS > statsInterval:
        prevStatisticsTS = now
        publishStats()
        for rel in relays:
            queryStatus(rel.index)

    try:
        data = msgqueue.get(block=True, timeout=waitTime)
        if data is None:
            continue
        msg = json.loads(data)
        processData(msg)

    except Empty:
        publishStats()  # contents are what was in previous queryStatus
        for rel in relays:
            queryStatus(rel.index) # querying again, results are shown later.
        waitTime = statsInterval

    except KeyboardInterrupt:
        client.disconnect()
        exit(0)

    except json.decoder.JSONDecodeError as e:
        print(datetime.utcnow(), "json:", e)
        print(datetime.utcnow(), data)

    except:
        raise
